[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@staking/=lib/frax-solidity/src/hardhat/contracts/Staking/',
    '@frax/=lib/frax-solidity/src/hardhat/contracts/',
    '@convex/=lib/frax-cvx-platform/contracts/contracts/',
    '@convex-platform/=lib/platform/contracts/',
    '@mocks/=test/mocks/',
    '@interfaces/=src/interfaces/'
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc_version = "0.8.17"
gas_reports = ["*"]

# settings for coverage reports
via_ir = true
optimizer = true #testing this out - was false
optimizer_runs = 100_000


[profile.default.optimizer_details]
jumpdestRemover = true
orderLiterals = true
deduplicate = true

yul = true
constantOptimizer = true
stackAllocation = true

# Have cse = true commented out for faster testing compilation, 
### but UNCOMMENT it for DEPLOYMENT! ###
#cse = true


[profile.default.optimizer_details.yulDetails]
stackAllocation = true

# Have optimizerSteps = "" uncommented for faster testing compilation, 
### but COMMENT IT out for DEPLOYMENT!###
optimizerSteps = ""


[profile.convex]
# `src` must be different fot it to work.
# We also recommend putting all Solidity test files and scripts inside `src*/`.
#src = 'src_convex'
#out = 'out'
# The order matters! When using `forge install` with FOUNDRY_PROFILE=0_6_x,
# it will use the first directory as the installation path.
# If the library is compatible with all versions,
# you can install it with the default profile.
#libs = ['lib_convex', 'lib']
#optimizer = true
#solc_version = '0.8.10'

# [profile.frax]
## `src` must be different fot it to work.
## We also recommend putting all Solidity test files and scripts inside `src*/`.
## src = 'src_frax'
## out = 'out'
## The order matters! When using `forge install` with FOUNDRY_PROFILE=0_6_x,
## it will use the first directory as the installation path.
## If the library is compatible with all versions,
## you can install it with the default profile.
# libs = ['lib_frax', 'lib']
# optimizer = true
# solc_version = '0.8.17'